/** Un pas de croche : une hauteur en Hz, ou `null` pour un silence. */
type AmbientStep = number | null;

export type AmbientTrack = {
  bpm: number;
  /**
   * Accords tenus, un par demi-mesure (cf. `CHORD_STEPS` dans audioFeedback) :
   * c'est la nappe qui donne la couleur d'accord sous la mélodie.
   */
  chords: readonly (readonly number[])[];
  /** Mélodie principale : une note par croche (boucle de 16 pas = 2 mesures). */
  melody: readonly AmbientStep[];
  /** Basse : une note par temps (boucle de 16 pas). */
  bass: readonly AmbientStep[];
  /** Arpège aigu, la brillance « chip » (boucle de 16 pas). */
  arp: readonly AmbientStep[];
  /** Percussion : une entrée par croche (boucle de 16 pas). */
  drums: readonly ("kick" | "snare" | "hat" | null)[];
};

const NOTE_SEMITONES: Record<string, number> = {
  C: 0,
  "C#": 1,
  Db: 1,
  D: 2,
  "D#": 3,
  Eb: 3,
  E: 4,
  F: 5,
  "F#": 6,
  Gb: 6,
  G: 7,
  "G#": 8,
  Ab: 8,
  A: 9,
  "A#": 10,
  Bb: 10,
  B: 11,
};

/**
 * Hauteur (Hz) depuis un nom de note scientifique : `note("C5")`, `note("Bb3")`.
 * Les boucles sont écrites en noms de notes pour rester vérifiables à l'œil
 * (armure, renversements, résolutions) : la musique se relit, pas les hertz.
 */
function note(name: string): number {
  const match = /^([A-G][#b]?)(-?\d)$/.exec(name);
  const semitone = match ? NOTE_SEMITONES[match[1]!] : undefined;
  if (semitone === undefined) throw new Error(`Note inconnue : ${name}`);
  const midi = (Number(match![2]) + 1) * 12 + semitone;
  return 440 * 2 ** ((midi - 69) / 12);
}

/**
 * Une identité musicale par monde (et non par niveau) : chaque boucle tient sur
 * deux mesures — nappe + basse + mélodie + arpège + percussion — dans une
 * tonalité et une progression propres au monde. Le monde 1 est lumineux et posé,
 * le 5 est le bouquet final avec sa dominante majeure (E) qui appelle la
 * tonique (Am). Aucune note hors accord n'est utilisée sur les temps forts.
 */
const WORLD_TRACKS: readonly AmbientTrack[] = [
  // Monde 1 — Découverte : Do majeur, I–V–vi–IV (C–G–Am–F), lumineux et posé.
  {
    bpm: 108,
    chords: [
      [note("C4"), note("E4"), note("G4")],
      [note("G3"), note("B3"), note("D4")],
      [note("A3"), note("C4"), note("E4")],
      [note("F3"), note("A3"), note("C4")],
    ],
    melody: [
      note("C5"),
      null,
      note("E5"),
      note("G5"),
      note("D5"),
      null,
      note("B4"),
      note("D5"),
      note("E5"),
      null,
      note("C5"),
      note("A4"),
      note("C5"),
      note("E5"),
      null,
      note("C5"),
    ],
    bass: [
      note("C3"),
      note("C3"),
      note("G3"),
      note("C3"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
      note("A2"),
      note("A2"),
      note("E3"),
      note("A2"),
      note("F2"),
      note("F2"),
      note("C3"),
      note("F2"),
    ],
    arp: [
      note("C6"),
      note("E6"),
      note("G6"),
      note("E6"),
      note("B5"),
      note("D6"),
      note("G6"),
      note("D6"),
      note("A5"),
      note("C6"),
      note("E6"),
      note("C6"),
      note("A5"),
      note("C6"),
      note("F6"),
      note("C6"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
    ],
  },
  // Monde 2 — Positionnement : La mineur, vi–IV–I–V (Am–F–C–G), plus mélancolique.
  {
    bpm: 114,
    chords: [
      [note("A3"), note("C4"), note("E4")],
      [note("F3"), note("A3"), note("C4")],
      [note("C4"), note("E4"), note("G4")],
      [note("G3"), note("B3"), note("D4")],
    ],
    melody: [
      note("A4"),
      null,
      note("C5"),
      note("E5"),
      note("F5"),
      null,
      note("C5"),
      note("A4"),
      note("E5"),
      note("D5"),
      null,
      note("C5"),
      note("B4"),
      note("D5"),
      null,
      note("B4"),
    ],
    bass: [
      note("A2"),
      note("A2"),
      note("E3"),
      note("A2"),
      note("F2"),
      note("F2"),
      note("C3"),
      note("F2"),
      note("C3"),
      note("C3"),
      note("G3"),
      note("C3"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
    ],
    arp: [
      note("A5"),
      note("C6"),
      note("E6"),
      note("C6"),
      note("F5"),
      note("A5"),
      note("C6"),
      note("A5"),
      note("C6"),
      note("E6"),
      note("G6"),
      note("E6"),
      note("B5"),
      note("D6"),
      note("G6"),
      note("D6"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      null,
      "snare",
      null,
      "hat",
      null,
      "kick",
      null,
      "hat",
      "kick",
      "snare",
      null,
      "hat",
      "hat",
    ],
  },
  // Monde 3 — Coordination : Ré mineur, i–VI–III–VII (Dm–Bb–F–C), plus tendu.
  {
    bpm: 122,
    chords: [
      [note("D4"), note("F4"), note("A4")],
      [note("Bb3"), note("D4"), note("F4")],
      [note("C4"), note("F4"), note("A4")],
      [note("C4"), note("E4"), note("G4")],
    ],
    melody: [
      note("D5"),
      null,
      note("F5"),
      note("D5"),
      note("Bb4"),
      null,
      note("D5"),
      note("F5"),
      note("F5"),
      null,
      note("C5"),
      note("A4"),
      note("C5"),
      note("E5"),
      null,
      note("C5"),
    ],
    bass: [
      note("D3"),
      note("D3"),
      note("A3"),
      note("D3"),
      note("Bb2"),
      note("Bb2"),
      note("F3"),
      note("Bb2"),
      note("F2"),
      note("F2"),
      note("C3"),
      note("F2"),
      note("C3"),
      note("C3"),
      note("G3"),
      note("C3"),
    ],
    arp: [
      note("A5"),
      note("D6"),
      note("F6"),
      note("D6"),
      note("Bb5"),
      note("D6"),
      note("F6"),
      note("D6"),
      note("C6"),
      note("F6"),
      note("A6"),
      note("F6"),
      note("C6"),
      note("E6"),
      note("G6"),
      note("E6"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
      "kick",
      null,
      "kick",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
    ],
  },
  // Monde 4 — Téléporteurs : Mi mineur, i–VI–III–VII (Em–C–G–D), mystérieux.
  {
    bpm: 128,
    chords: [
      [note("E4"), note("G4"), note("B4")],
      [note("C4"), note("E4"), note("G4")],
      [note("G3"), note("B3"), note("D4")],
      [note("D4"), note("F#4"), note("A4")],
    ],
    melody: [
      note("E5"),
      null,
      note("G5"),
      note("E5"),
      note("C5"),
      null,
      note("E5"),
      note("G5"),
      note("G5"),
      null,
      note("D5"),
      note("B4"),
      note("D5"),
      note("F#5"),
      null,
      note("D5"),
    ],
    bass: [
      note("E3"),
      note("E3"),
      note("B3"),
      note("E3"),
      note("C3"),
      note("C3"),
      note("G3"),
      note("C3"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
      note("D3"),
      note("D3"),
      note("A3"),
      note("D3"),
    ],
    arp: [
      note("B5"),
      note("D6"),
      note("E6"),
      note("D6"),
      note("C6"),
      note("E6"),
      note("G6"),
      note("E6"),
      note("B5"),
      note("D6"),
      note("G6"),
      note("D6"),
      note("A5"),
      note("D6"),
      note("F#6"),
      note("D6"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      null,
      "snare",
      null,
      "hat",
      null,
      "kick",
      null,
      "hat",
      "kick",
      "snare",
      "hat",
      "hat",
      "hat",
    ],
  },
  // Monde 5 — Portes : La mineur, i–VI–VII–V majeur (Am–F–G–E) : la dominante
  // majeure (G#) appelle la tonique, la boucle pousse vers le niveau suivant.
  {
    bpm: 134,
    chords: [
      [note("A3"), note("C4"), note("E4")],
      [note("F3"), note("A3"), note("C4")],
      [note("G3"), note("B3"), note("D4")],
      [note("E3"), note("G#3"), note("B3")],
    ],
    melody: [
      note("A4"),
      null,
      note("C5"),
      note("E5"),
      note("F5"),
      null,
      note("C5"),
      note("A4"),
      note("B4"),
      note("D5"),
      note("G5"),
      note("B4"),
      note("G#5"),
      null,
      note("E5"),
      note("B4"),
    ],
    bass: [
      note("A2"),
      note("A2"),
      note("E3"),
      note("A2"),
      note("F2"),
      note("F2"),
      note("C3"),
      note("F2"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
      note("E2"),
      note("E2"),
      note("B2"),
      note("E2"),
    ],
    arp: [
      note("A5"),
      note("C6"),
      note("E6"),
      note("C6"),
      note("F5"),
      note("A5"),
      note("C6"),
      note("A5"),
      note("G5"),
      note("B5"),
      note("D6"),
      note("B5"),
      note("E5"),
      note("G#5"),
      note("B5"),
      note("G#5"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
      "kick",
      "hat",
      "kick",
      "hat",
      "snare",
      "hat",
      "hat",
      "snare",
    ],
  },
];

const SEASONAL_TRACKS: Readonly<Record<string, AmbientTrack>> = {
  // Halloween : Ré mineur, i–VI–iv–V (Dm–Bb–Gm–A), le V majeur (C#) fait peur.
  halloween: {
    bpm: 116,
    chords: [
      [note("D4"), note("F4"), note("A4")],
      [note("Bb3"), note("D4"), note("F4")],
      [note("G3"), note("Bb3"), note("D4")],
      [note("A3"), note("C#4"), note("E4")],
    ],
    melody: [
      note("D5"),
      null,
      note("F5"),
      note("D5"),
      note("Bb4"),
      note("D5"),
      null,
      note("Bb4"),
      note("G4"),
      note("Bb4"),
      note("D5"),
      note("Bb4"),
      note("C#5"),
      note("A4"),
      note("C#5"),
      note("E5"),
    ],
    bass: [
      note("D3"),
      note("D3"),
      note("A3"),
      note("D3"),
      note("Bb2"),
      note("Bb2"),
      note("F3"),
      note("Bb2"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
      note("A2"),
      note("A2"),
      note("E3"),
      note("A2"),
    ],
    arp: [
      note("A5"),
      note("D6"),
      note("F6"),
      note("D6"),
      note("Bb5"),
      note("D6"),
      note("F6"),
      note("D6"),
      note("G5"),
      note("Bb5"),
      note("D6"),
      note("Bb5"),
      note("A5"),
      note("C#6"),
      note("E6"),
      note("C#6"),
    ],
    drums: [
      "kick",
      null,
      null,
      "hat",
      null,
      "snare",
      null,
      "hat",
      "kick",
      null,
      "hat",
      null,
      "snare",
      null,
      null,
      "hat",
    ],
  },
  // Noël : Do majeur, I–vi–IV–V (C–Am–F–G), carillon simple et chaloupé.
  christmas: {
    bpm: 104,
    chords: [
      [note("C4"), note("E4"), note("G4")],
      [note("A3"), note("C4"), note("E4")],
      [note("F3"), note("A3"), note("C4")],
      [note("G3"), note("B3"), note("D4")],
    ],
    melody: [
      note("C5"),
      note("E5"),
      note("C5"),
      note("G4"),
      note("A4"),
      note("C5"),
      note("E5"),
      note("C5"),
      note("F5"),
      note("C5"),
      note("A4"),
      null,
      note("B4"),
      note("D5"),
      note("B4"),
      note("G4"),
    ],
    bass: [
      note("C3"),
      note("C3"),
      note("G3"),
      note("C3"),
      note("A2"),
      note("A2"),
      note("E3"),
      note("A2"),
      note("F2"),
      note("F2"),
      note("C3"),
      note("F2"),
      note("G2"),
      note("G2"),
      note("D3"),
      note("G2"),
    ],
    arp: [
      note("C6"),
      note("E6"),
      note("G6"),
      note("E6"),
      note("A5"),
      note("C6"),
      note("E6"),
      note("C6"),
      note("F5"),
      note("A5"),
      note("C6"),
      note("A5"),
      note("B5"),
      note("D6"),
      note("G6"),
      note("D6"),
    ],
    drums: [
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
      "kick",
      null,
      "hat",
      "hat",
      "snare",
      null,
      "hat",
      "hat",
    ],
  },
};

function getWorldNumber(levelId?: string) {
  const match = levelId?.match(/^world-(\d+)-level-\d+$/);
  return Number(match?.[1] ?? 1);
}

export function getAmbientTrackKey(
  levelId?: string,
  skin: "default" | "halloween" | "christmas" = "default",
) {
  if (skin !== "default") return `skin:${skin}`;
  return `world:${getWorldNumber(levelId)}`;
}

/** Resolve one stable musical identity for a world/theme. */
export function getAmbientTrack(
  levelId?: string,
  skin: "default" | "halloween" | "christmas" = "default",
): AmbientTrack {
  if (skin !== "default") {
    return SEASONAL_TRACKS[skin] ?? WORLD_TRACKS[0]!;
  }

  const world = getWorldNumber(levelId);
  return WORLD_TRACKS[(world - 1) % WORLD_TRACKS.length] ?? WORLD_TRACKS[0]!;
}
